topmusic/topmusic/urls.py
from django.contrib import admin, auth
from django.contrib.auth import views as auth_views
from django.urls import path
from topmusicapp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name="home"),
    path('dashboard', views.dashboard, name='dashboard'),
    # AUTH
    path('signup', views.SignUp.as_view(), name='signup'),
    # this references a priori as template registration/login.html
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),

    # Playlist
    path('playlist/create', views.CreatePlaylist.as_view(), name='create_playlist'),
    path('playlist/<int:pk>', views.DetailPlaylist.as_view(), name='detail_playlist'),
    path('playlist/<int:pk>/update',
         views.UpdatePlaylist.as_view(), name='update_playlist'),
    path('playlist/<int:pk>/delete',
         views.DeletePlaylist.as_view(), name='delete_playlist'),
    # Video
    path('playlist/<int:pk>/addvideo', views.add_video, name='add_video'),
    path('video/search', views.video_search, name='video_search'),
    path('video/<int:pk>/delete',
         views.DeleteVideo.as_view(), name='delete_video'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

topmusic/topmusicapp/models.py
from django.db import models
from django.contrib.auth.models import User


class MusicPlaylist(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Video(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    playlist = models.ForeignKey(MusicPlaylist, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.id)

topmusic/topmusicapp/forms.py
from .models import Video
from django import forms

# automatically creates a form for you based on the model passed


class VideoForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ['url']
        labels = {'url': 'Youtube Url'}


class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=255, label="Search for Videos:")

topmusic/topmusicapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, JsonResponse
from django.forms.utils import ErrorList
from .models import MusicPlaylist, Video
from .forms import VideoForm, SearchForm
import urllib
import requests


def home(request):
    recent_playlists = MusicPlaylist.objects.all().order_by('-id')[:3]
    popular_playlists = MusicPlaylist.objects.all()
    return render(request, 'topmusicapp/home.html', {'recent_playlists': recent_playlists, 'popular_playlists': popular_playlists})


@login_required
def dashboard(request):
    playlists = MusicPlaylist.objects.filter(user=request.user)
    return render(request, 'topmusicapp/dashboard.html', {'playlists': playlists})


@login_required
def add_video(request, pk):
    form = VideoForm()
    search_form = SearchForm()
    playlist = MusicPlaylist.objects.get(pk=pk)
    if not playlist.user == request.user:
        raise Http404

    if request.method == "POST":
        form = VideoForm(request.POST)
        if form.is_valid():
            video = Video()
            video.playlist = playlist
            video.url = form.cleaned_data['url']
            parsed_url = urllib.parse.urlparse(video.url)
            video_id = urllib.parse.parse_qs(parsed_url.query).get('v')
            if video_id:
                video.youtube_id = video_id[0]
                response = requests.get(
                    f'https://youtube.googleapis.com/youtube/v3/videos?part=snippet&id={video_id[0]}&key={YOUTUBE_API_KEY}')
                json = response.json()
                title = json['items'][0]['snippet']['title']
                video.title = title
                video.save()
                return redirect('detail_playlist', pk)
            else:
                errors = form._errors.setdefault('url', ErrorList())
                errors.append('Needs to be a Youtube url')
    return render(request, 'topmusicapp/addvideo.html', {'form': form, 'search_form': search_form, 'playlist': playlist})


@login_required
def video_search(request):
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(
            search_form.cleaned_data['search_term'])
        response = requests.get(
            f'https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=5&q={encoded_search_term}&key={YOUTUBE_API_KEY}')
        return JsonResponse(response.json())
    return JsonResponse({'error': 'Not able to validate form'})


class DeleteVideo(LoginRequiredMixin, generic.DeleteView):
    model = Video
    template_name = 'topmusicapp/deletevideo.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        video = super(DeleteVideo, self).get_object()
        if not video.playlist.user == self.request.user:
            raise Http404
        return video


class SignUp(generic.CreateView):
    # passes it to the template as 'form' which you can then use there
    form_class = UserCreationForm
    success_url = reverse_lazy('home')
    template_name = 'registration/signup.html'

    def form_valid(self, form):
        view = super(SignUp, self).form_valid(form)
        username, password = form.cleaned_data.get(
            'username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view


class CreatePlaylist(LoginRequiredMixin, generic.CreateView):
    model = MusicPlaylist
    fields = ['title']
    template_name = 'topmusicapp/createplaylist.html'
    success_url = reverse_lazy('dashboard')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(CreatePlaylist, self).form_valid(form)
        return redirect('dashboard')


class DetailPlaylist(generic.DetailView):
    model = MusicPlaylist
    template_name = 'topmusicapp/detailplaylist.html'


class UpdatePlaylist(LoginRequiredMixin, generic.UpdateView):
    model = MusicPlaylist
    template_name = 'topmusicapp/updateplaylist.html'
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        musicplaylist = super(UpdatePlaylist, self).get_object()
        if not musicplaylist.user == self.request.user:
            raise Http404
        return musicplaylist


class DeletePlaylist(LoginRequiredMixin, generic.DeleteView):
    model = MusicPlaylist
    template_name = 'topmusicapp/deleteplaylist.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        musicplaylist = super(DeletePlaylist, self).get_object()
        if not musicplaylist.user == self.request.user:
            raise Http404
        return musicplaylist

topmusic/topmusicapp/templates/topmusicapp/addvideo.html
{% extends 'topmusicapp/base.html' %}  {% block content %}
<br>
<div class="container">
  <h2>Add video to {{playlist.title}}</h2>
  <form method="POST" id="submit_video">
    {% csrf_token %} {% load widget_tweaks %} {% for field in form %}
    <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
      {{field.errors}} 
      {{field.label_tag}}                 
      {% render_field field class="form-control" %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-danger">Add</button>
  </form>
<br><br>
  <h2>OR</h2>
  <form>{% for field in search_form %}
    <div class="form-group">
      {{field.errors}} 
      {{field.label_tag}}                 
      {% render_field field class="form-control" %}
    </div>
    {% endfor %}</form>
    <div id="search_results"></div>
    <script>
    var delayTimer;
    $('#id_search_term').keyup(function() {
      clearTimeout(delayTimer);
      $('#search_results').text('Loading...');
      delayTimer = setTimeout(function() {
        var text = $('#id_search_term').val();
        $.ajax({
          url: '/video/search',
          data: {
            'search_term': text
          },
          dataType: 'json',
          success: function(data) {
            var results = '';
            $('#search_results').text('');
            results += '<div class="row">';
            data['items'].forEach(function(video){
              results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
              results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/' + video['id']['videoId'] + '"title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>'
              results += '<div class="card-body"><p class="card-text">' + video['snippet']['title'] + '</p>';
              results += '<a href="#" class="btn btn-danger" onclick="addVideo(\'' + video['id']['videoId'] + '\')"> Add </a> </div></div></div>';
            });
            results += '</div>';
            $('#search_results').append(results);
          }
        });
      }, 2000)
    });

    function addVideo(video_id) {
      $('#id_url').val('https://www.youtube.com/watch?v=' + video_id);
      $('#submit_video').submit();
    }
    </script>
</div>
{% endblock %}

topmusic/topmusicapp/templates/topmusicapp/base.html
<!DOCTYPE html>
<html lang="en">
  {% load static %}

  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <title>Music Playlists</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css"
      integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
      crossorigin="anonymous"
    />
    <link href="{% static 'custom.css' %}" rel="stylesheet" />
    <link
      rel="shortcut icon"
      type="titleicon/jpg"
      href="{% static 'titleicon.jpg' %}"
    />
  </head>

  <body>
    <div
      class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm"
    >
      <h5 class="my-0 mr-md-auto font-weight-normal">
        <a href="{% url 'home' %}" class="text-dark">My most beloved music</a>
      </h5>
      <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        <a class="p-2 text-dark" href="{% url 'dashboard' %}">Dashboard</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Log Out</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Log In</a>
        {% endif %}
      </nav>
      {% if user.is_authenticated == False %}
      <a class="btn btn-outline-danger" href="{% url 'signup' %}">Sign up</a>
      {% endif %}
    </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
    crossorigin="anonymous"
  ></script>
    {% block content %} {% endblock %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  
  </body>
</html>

topmusic/topmusicapp/templates/topmusicapp/createplaylist.html
{% extends 'topmusicapp/base.html' %} {% block content %}
<div class="container">
  <h2>Create playlist</h2>
  <form method="POST">
    {% csrf_token %} {% load widget_tweaks %} {% for field in form %}
    <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
      {{field.errors}} 
      {{field.label_tag}}                 
      {% render_field field class="form-control" %}
    </div>
    {% endfor %}
    <button type="submit" class="btn btn-danger"/>Create</button>
  </form>
</div>
{% endblock %}

topmusic/topmusicapp/templates/topmusicapp/dashboard.html
{% extends 'topmusicapp/base.html' %} {% block content %}
<div class="container">
  <div class="text-center ">
    <h2>{{user.username}}'s Playlist</h2>
    <a href="{% url 'create_playlist' %}" class="btn btn-danger m-2">Create a new playlist</a>
  </div>

               {% for playlist in playlists %}
  <h2> <a href="{% url 'detail_playlist' playlist.id %}">{{playlist.title}}</a></h2>
  <a href="{% url 'delete_playlist' playlist.id %}" class="btn btn-dark m-2">Delete this playlist</a>
  <a href="{% url 'update_playlist' playlist.id %}" class="btn btn-info m-2">Edit this playlist</a>
  <a href="{% url 'add_video' playlist.id %}" class="btn btn-danger m-2">Add video</a>
    <div class="row">
     {% for video in playlist.video_set.all %}
      <div class="col-md-4 mt-3">
        <div class="card mb-4 shadow-sm">
         <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.youtube_id}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
         <div class="card-body">
          <p class="card-text">{{video.title}}</p>
         </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% endfor %}
     </div>
{% endblock %}

topmusic/topmusicapp/templates/topmusicapp/deleteplaylist.html
{% extends 'topmusicapp/base.html' %} {% block content %}
<div class="container">
  <h2>Are you sure you want to delete this playlist?</h2>
  <form method="POST">
    {% csrf_token %}{{form.as_p}}<button type="submit" class="btn btn-danger">
      Delete
    </button>
  </form>

  <br />
  <h2>
    <a href="{% url 'detail_playlist' musicplaylist.id %}"
      >{{musicplaylist.title}}</a
    >
  </h2>
</div>
{% endblock %}

topmusic/topmusicapp/templates/topmusicapp/deletevideo.html
{% extends 'topmusicapp/base.html' %} {% block content %}
<div class="container">
  <h2>Are you sure you want to delete this video?</h2>
  <form method="POST">
    {% csrf_token %}{{form.as_p}}<button type="submit" class="btn btn-danger">
      Delete
    </button>
  </form>
  <br>
 <a href="{% url 'dashboard' %}"><button type="submit" class="btn btn-danger">No, go back</button></a>
<div class="row">
<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">
 <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.youtube_id}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
 <div class="card-body"><p class="card-text">{{video.title}}</p>
  </div></div></div>
 </div>
</div>
{% endblock %}

topmusic/topmusicapp/templates/topmusicapp/detailplaylist.html
{% extends 'topmusicapp/base.html' %} {% block content %}
<div class="container">
  <h1>{{musicplaylist.title}}</h1>
  <h4 class="text-muted">{{musicplaylist.user.username}}</h4>
  {% if user.id == musicplaylist.user.id %}
  <a href="{% url 'delete_playlist' musicplaylist.id %}" class="btn btn-dark m-2">Delete this playlist</a>
  <a href="{% url 'update_playlist' musicplaylist.id %}" class="btn btn-danger m-2">Edit this playlist</a>
  <a href="{% url 'add_video' musicplaylist.id %}" class="btn btn-danger m-2">Add video</a>
  {% endif %}
    <div class="row">
     {% for video in musicplaylist.video_set.all %}
      <div class="col-md-4 mt-3">
        <div class="card mb-4 shadow-sm">
         <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{video.youtube_id}}" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
         <div class="card-body">
          <p class="card-text">{{video.title}}</p>
          {% if user.id == musicplaylist.user.id %}
          <a href="{% url 'delete_video' video.id %}" class="btn btn-dark m-2">Delete this video</a>
          {% endif %}
         </div>
        </div>
      </div>
      {% endfor %}
    </div>
</div>
{% endblock %}

topmusic/topmusicapp/templates/topmusicapp/home.html
{% extends 'topmusicapp/base.html' %}
{% block content %}
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">What's your favorite music?</h1>
    <p class="lead text-muted">Make your own playlist and show it to other people. Click the button below to get started</p>
    <p>
      <a href="{% url 'create_playlist' %}" class="btn btn-danger">Create Your Music Playlist</a>
    </p>
  </div>
</section>
<div class="container">
  <h1 class="text-center">Popular Playlists</h1>
  {% for playlist in popular_playlists %}

<h2><a href="{% url 'detail_playlist' playlist.id %}">{{ playlist.title }}</a></h2>

  <div class="row">
    {% for video in playlist.video_set.all %}
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body">
          <p class="card-text">{{ video.title }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
    </div>
  {% endfor %}


  <h1 class="text-center">Recent Playlists</h1>
  {% for playlist in recent_playlists %}

<h2><a href="{% url 'detail_playlist' playlist.id %}">{{ playlist.title }}</a></h2>

  <div class="row">
    {% for video in playlist.video_set.all %}
    <div class="col-md-4 mt-3">
      <div class="card mb-4 shadow-sm">
        <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        <div class="card-body">
          <p class="card-text">{{ video.title }}</p>
        </div>
      </div>
    </div>
    {% endfor %}
    </div>
  {% endfor %}


</div>
{% endblock %}

topmusic/topmusicapp/templates/topmusicapp/updateplaylist.html
{% extends 'topmusicapp/base.html' %} {% block content %}
<div class="container">
  <h2>Edit playlist</h2>
  <form method="POST">
    {% csrf_token %}{% load widget_tweaks %} {% for field in form %}
    <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
      {{field.errors}} 
      {{field.label_tag}}                 
      {% render_field field class="form-control" %}
    </div>
    {% endfor %}<button type="submit" class="btn btn-dark"/>Save</button>
  </form>
<br>
  <a href="{% url 'delete_playlist' musicplaylist.id %}" class="btn btn-danger">Delete this playlist</a>
</div>
{% endblock %}